import uuid
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel


class BudgetInsight(BaseModel):
    """A single budgeting insight / tip generated by the rule-based engine."""

    id: str  # e.g. "over_budget_dining_2026_09"
    type: str  # over_budget, under_budget, no_budget_high_spend, spending_spike, savings_opportunity, recurring_review, goal_pace
    severity: str  # info, warning, success
    title: str
    description: str
    category_id: Optional[uuid.UUID] = None
    amount: Optional[Decimal] = None
    suggestion: Optional[str] = None
    action_url: Optional[str] = None  # deep link to relevant page
